---
- name: Copy Kernel 4.19.1-1
  copy:
    src: kernel-ml-4.19.1-1.el7.elrepo.x86_64.rpm
    dest: /tmp/
    mode: 644

- name: Install Kernel
  yum:
    name: /tmp/kernel-ml-4.19.1-1.el7.elrepo.x86_64.rpm
    state: present

- name: Fix
  shell: sed -i 's/GRUB_DEFAULT=saved/GRUB_DEFAULT=0/g' /etc/default/grub

- name: Fix
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: sysctl
  shell: sed -i '/net\.core\.default_qdisc=fq/d' /etc/sysctl.conf

- name: sysctl
  shell: sed -i '/net\.ipv4\.tcp_congestion_control=bbr/d' /etc/sysctl.conf

- name: BBR
  shell: echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf

- name: BBR
  shell: echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf

- name: Copy Kernel 4.19.1-1
  file:
    path: /tmp/kernel-ml-4.19.1-1.el7.elrepo.x86_64.rpm
    state: absent
